name: Build and Push Backend Image

on:
  push:
    branches: [master]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ubuntu-latest-node-v23-deps-${{ hashFiles('package-lock.json') }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            itisnotstupid/chess-backend:latest
            itisnotstupid/chess-backend:${{ github.sha }}
